version: '3.8'

services:
  restaurant-service:
    build:
      context: ./restaurant_service
      dockerfile: DockerFile
    container_name: ds-assignment-restaurant-service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://sm:mihi@cluster0.aslaq.mongodb.net/Finace_Tracker
      - JWT_SECRET=yourSuperSecretKey
      - JWT_EXPIRES_IN=1h
      - ORDER_SERVICE_URL=http://order-service:5005/api/orders
    volumes:
      - ./restaurant_service/public/uploads:/app/public/uploads

  order-service:
    build:
      context: ./order_service
      dockerfile: DockerFile
    container_name: ds-assignment-order-service
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - MONGO_URI=mongodb+srv://vikummune123:VIk123abc@cluster1.2sye1.mongodb.net/order?retryWrites=true&w=majority&appName=Cluster1
      - JWT_SECRET=yourSuperSecretKey
      - JWT_EXPIRES_IN=1h
  payment-service:
    build:
      context: ./payment_service
      dockerfile: DockerFile
    container_name: ds-assignment-payment-service
    ports:
      - "5004:5004"
    environment:
      - PORT=5004
      - MONGO_URI=mongodb+srv://vikummune123:VIk123abc@cluster1.2sye1.mongodb.net/order?retryWrites=true&w=majority&appName=Cluster1
      - JWT_SECRET=yourSuperSecretKey
      - JWT_EXPIRES_IN=1h
      - FRONTEND_URL=http://localhost:5173
  delivery-service:
    build:
      context: ./delivery_service
      dockerfile: DockerFile
    container_name: ds-assignment-delivery-service
    ports:
      - "5006:5006"
    environment:
      - PORT=5006
      - MONGO_URI=mongodb+srv://vikummune123:VIk123abc@cluster1.2sye1.mongodb.net/order?retryWrites=true&w=majority&appName=Cluster1
      - JWT_SECRET=yourSuperSecretKey
      - JWT_EXPIRES_IN=1h
      - ORDER_SERVICE_URL=http://order-service:5005/api/orders
      - FRONTEND_URL=http://localhost:5173
      - DELIVERY_SERVICE_URL=http://delivery-service:5006

  auth-service:
    build:
      context: ./auth_service
      dockerfile: DockerFile
    container_name: ds-assignment-auth-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGO_URI=mongodb+srv://vikummune123:VIk123abc@cluster1.2sye1.mongodb.net/order?retryWrites=true&w=majority&appName=Cluster1
      - JWT_SECRET=yourSuperSecretKey
      - JWT_EXPIRES_IN=1h

  admin-service:
    build:
      context: ./admin_service
      dockerfile: DockerFile
    container_name: ds-assignment-admin-service
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - MONGO_URI=mongodb+srv://vikummune123:VIk123abc@cluster1.2sye1.mongodb.net/order?retryWrites=true&w=majority&appName=Cluster1
      - JWT_SECRET=yourSuperSecretKey
      - JWT_EXPIRES_IN=1h
      - AUTH_SERVICE_URL=http://auth-service:5002/api/auth
      - RESTAURANT_SERVICE_URL=http://restaurant-service:5000/api/restaurants
      - PAYMENT_SERVICE_URL=http://payment-service:5004/api/payments

  frontend:
    build:
      context: ../tailwind-react-frontend
      dockerfile: Dockerfile
    container_name: ds-assignment-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:5000/api
      - VITE_RESTAURANT_API_BASE_URL=http://localhost:5000/api/restaurants
      - VITE_AUTH_API_BASE_URL=http://localhost:5002/api/auth
      - VITE_DELIVERY_API_BASE_URL=http://localhost:5006/api
      - VITE_ORDER_API_BASE_URL=http://localhost:5005/api/orders
      - VITE_ADMIN_API_BASE_URL=http://localhost:5050/api/admin
      - VITE_PAYMENT_API_BASE_URL=http://localhost:5004/api/payments
    depends_on:
      - restaurant-service
      - auth-service
      - order-service
      - payment-service
      - delivery-service
      - admin-service